server:
  port: 8000

spring:
  application:
    name: task-manager-api

  datasource:
    url: jdbc:postgresql://localhost:5433/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 30000

    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: validate
      show-sql: false
      properties:
        hibernate:
          format_sql: true
          jdbc:
            batch_size: 1000
            time_zone: UTC
          order_inserts: true
          order_updates: true

    flyway:
      enabled: true
      clean-disabled: false   # true em PROD
      locations: classpath:db/migration

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: ${JWT_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus

        endpoint:
          health:
            show-details: always

        metrics:
          tags:
            application: ${spring.application.name}

  info:
    env:
      enabled: true
    build:
      enabled: true
    git:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    environment: ${SPRING_PROFILES_ACTIVE:default}
    category: Backend REST API
    api-version: v1
    authentication: JWT
    database: PostgreSQL
    migration: Flyway
    observability:
      metrics: Prometheus + Grafana
      logging: Loki + Promtail
    documentation: Swagger/OpenAPI

  build:
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}
    artifact: ${project.artifactId}
    group: ${project.groupId}
    time: ${maven.build.timestamp}

  technology:
    language: Java
    java-version: ${java.version}
    framework: Spring Boot

  contact:
    team: Backend Team

  features:
    authentication: JWT
    database-migration: Flyway
    monitoring: Prometheus + Grafana
    logging: Loki + Promtail

  git:
    branch: ${git.branch}
    commit:
      id: ${git.commit.id}
      time: ${git.commit.time}